name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  USERNAME: ma3ve
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout to the tagged commit
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}

